# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
        # node-version: [12.x, 14.x]
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci # - run: npm run build --if-present # n/a
    - run: npm test

  post-commit-status:
    runs-on: ubuntu-latest
    steps:
    # Check out code using git
    - uses: actions/checkout@v2
    # Install Node 12
    - run: echo DO NOTHING?
    # - uses: actions/setup-node@v1
    #   with:
    #     node-version: 12
    # - run: node .github/actions/post-commit-status.js
    #   with:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
